# Generated by Django 4.2.20 on 2025-06-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del artículo')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU (Código único)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Visible para clientes?')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Artículo destacado?')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='articulos_principales/', verbose_name='Imagen Principal del Artículo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_at', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloFiltroValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.articulo', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Filtro Aplicado a Artículo',
                'verbose_name_plural': 'Filtros Aplicados a Artículos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, help_text='Dejar en blanco para autogenerar', max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('imagen_categoria', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen de la Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave de configuración')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del filtro')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Filtro activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Filtro',
                'verbose_name_plural': 'Tipos de Filtros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo (opcional)')),
                ('imagen', models.ImageField(upload_to='banco_imagenes/', verbose_name='Archivo de imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Banco de Imágenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiltroValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor del filtro')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Hexadecimal del Color (ej: #FF0000)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Valor activo?')),
                ('articulos', models.ManyToManyField(blank=True, related_name='filtros_aplicados', through='ecommerce_app.ArticuloFiltroValor', to='ecommerce_app.articulo', verbose_name='Artículos con este filtro')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ecommerce_app.filtro', verbose_name='Tipo de Filtro')),
            ],
            options={
                'verbose_name': 'Valor de Filtro',
                'verbose_name_plural': 'Valores de Filtros',
                'ordering': ['filtro', 'valor'],
                'unique_together': {('filtro', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ArticuloImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es imagen principal?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en la galería')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.articulo', verbose_name='Artículo')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.imagen', verbose_name='Imagen del Banco')),
            ],
            options={
                'verbose_name': 'Imagen de Artículo',
                'verbose_name_plural': 'Imágenes de Artículos',
                'ordering': ['articulo', 'orden'],
                'unique_together': {('articulo', 'imagen')},
            },
        ),
        migrations.AddField(
            model_name='articulofiltrovalor',
            name='filtro_valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.filtrovalor', verbose_name='Valor de Filtro'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='ecommerce_app.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagenes_galeria',
            field=models.ManyToManyField(blank=True, related_name='articulos_galeria', through='ecommerce_app.ArticuloImagen', to='ecommerce_app.imagen', verbose_name='Imágenes de Galería'),
        ),
        migrations.AlterUniqueTogether(
            name='articulofiltrovalor',
            unique_together={('articulo', 'filtro_valor')},
        ),
    ]
