# Generated by Django 5.2.1 on 2025-06-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Identificador del carrusel (ej: 'principal', 'ofertas')", max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.SlugField(help_text="Identificador único para este bloque (ej: 'banner-bienvenida-home', 'aviso-envios')", max_length=100, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido_html', models.TextField(blank=True, help_text='Contenido principal del bloque. Puede ser HTML.', null=True)),
                ('imagen_asociada', models.ImageField(blank=True, null=True, upload_to='content_blocks/')),
                ('enlace_url', models.URLField(blank=True, help_text='URL a la que podría enlazar este bloque (opcional)', max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque de Contenido',
                'verbose_name_plural': 'Bloques de Contenido',
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_del_enlace', models.CharField(max_length=100)),
                ('url_o_ruta', models.CharField(help_text='URL completa (ej: https://ejemplo.com) o ruta interna (ej: /tienda)', max_length=300)),
                ('ubicacion', models.CharField(choices=[('header', 'Cabecera'), ('footer_col1', 'Pie de Página - Columna 1'), ('footer_col2', 'Pie de Página - Columna 2')], default='header', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('abrir_en_nueva_pestana', models.BooleanField(default=False, help_text='Marcar si el enlace debe abrirse en una nueva pestaña')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enlace de Navegación',
                'verbose_name_plural': 'Enlaces de Navegación',
                'ordering': ['ubicacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carousels/', verbose_name='Imagen del slide')),
                ('titulo', models.CharField(blank=True, help_text='Título opcional que se superpone a la imagen', max_length=200, null=True)),
                ('subtitulo', models.TextField(blank=True, help_text='Subtítulo o descripción opcional', null=True)),
                ('enlace_url', models.URLField(blank=True, help_text='URL a la que enlaza el slide (opcional)', max_length=300, null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición del slide')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='ecommerce_app.carousel')),
            ],
            options={
                'verbose_name': 'Slide de Carrusel',
                'verbose_name_plural': 'Slides de Carrusel',
                'ordering': ['carousel', 'orden'],
            },
        ),
    ]
