"""
Django settings for diegojhoao_project project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qle_6b2t@h$_z2l__r06dmh$))tt@#60a#g0hen(%^-n&w+ocv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Para producción en Render:
# Render establece automáticamente la variable de entorno RENDER_EXTERNAL_HOSTNAME
# con el nombre de host público de tu servicio.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Para desarrollo local (si DEBUG es True):
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Application definition

INSTALLED_APPS = [
        'jazzmin',  

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps (ej: ecommerce_app)
    'ecommerce_app.apps.EcommerceAppConfig', # O simplemente 'ecommerce_app'

    # Apps de terceros
    'django_filters',
    'rest_framework',
    'corsheaders',
]

# diegojhoao_project/settings.py

# ... (resto de tu configuración) ...

JAZZMIN_SETTINGS = {
    # Título en la pestaña del navegador y en la cabecera de la página de login (predeterminado por site_header)
    "site_title": "DiegoJhoao Admin",

    # Título en la cabecera (predeterminado por site_header si no se establece)
    "site_header": "DiegoJhoao",

    # Título en el logo (predeterminado por site_header si no se establece)
    # Puedes usar una abreviatura aquí si el site_header es demasiado largo.
    "site_brand": "DiegoJhoao",

    # Logo para la página de login, forma oscura (ruta estática)
    # "login_logo_dark": None, # Comentado si no tienes uno oscuro específico

    # Logo para el panel de administración, versión clara (ruta estática)
    # "site_logo": "img/logo_tienda_admin.png", # Ejemplo: pon tu logo en static/img/

    # Logo para el panel de administración, versión oscura (ruta estática)
    # "site_logo_dark": "img/logo_tienda_admin_dark.png", # Ejemplo

    # Clases CSS para aplicar al logo
    # "site_logo_classes": "img-circle", # Hace el logo circular si es cuadrado

    # Bienvenido (página de inicio del admin)
    "welcome_sign": "Bienvenido al panel de administración de DiegoJhoao.store",

    # Copyright en el pie de página
    "copyright": "DiegoJhoao.store Ltd.",

    # El modelo django auth User para buscar (predeterminado User)
    # "user_avatar": "ruta.a.campo.avatar.del.usuario", # Si tienes avatares para usuarios

    ############
    # Top Menu #
    ############
    # Enlaces que quieres en la barra de menú superior
    # P.ej., un enlace a tu sitio web principal
    

    ############
    # UI Customizer #
    ############
    # Mostrar el personalizador de UI en la esquina superior derecha
    "show_ui_builder": True, # ¡MUY ÚTIL para probar temas y opciones visuales!

    ###############
    # Change view #
    ###############
    # Cómo se muestran los botones de guardar en la página de edición
    "changeform_format": "horizontal_tabs", # Otras opciones: 'vertical_tabs', 'collapsible', 'single'
    # # Anular el formato por modelo
    # "changeform_format_overrides": {
    #     "auth.user": "collapsible",
    #     "auth.group": "vertical_tabs",
    # },
}

# Opcional: Configuración de UI (más detallada, puedes ajustarla con el UI Builder)
# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": "navbar-primary", # "navbar-indigo", "navbar-purple", etc.
#     "accent": "accent-primary", # "accent-teal", "accent-orange", etc.
#     "navbar": "navbar-dark", # "navbar-white navbar-light"
#     "no_navbar_border": False,
#     "navbar_fixed": True,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": True,
#     "sidebar": "sidebar-dark-primary", # "sidebar-light-primary", etc.
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": False,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": False,
#     "theme": "default", # "darkly", "cerulean", "cosmo", "flatly", "journal", "litera", "lumen", "lux", "materia", "minty", "pulse", "sandstone", "simplex", "sketchy", "slate", "solar", "spacelab", "superhero", "united", "yeti"
#     "dark_mode_theme": "darkly", # Tema a usar si el tema por defecto no es oscuro y se activa el modo oscuro
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     }
# }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # ¡AÑADIR ESTO ARRIBA!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # ASEGÚRATE DE ESTO

]

ROOT_URLCONF = 'diegojhoao_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # ESTA LÍNEA ES CLAVE

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'diegojhoao_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuración de Django REST Framework (opcional por ahora, pero útil más adelante)
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # Por defecto, permitir cualquier acceso. Puedes restringirlo más tarde.
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [ 
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}

# Configuración de CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # El puerto donde se ejecuta tu app React
    "http://127.0.0.1:3000", # Alternativa para localhost
    "https://diegojhoao.onrender.com",  # ¡AÑADE ESTA LÍNEA CON LA URL EXACTA DE TU FRONTEND!

]
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# diegojhoao_project/settings.py

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
